#ifndef RIPPLEDEFINES_H
#define RIPPLEDEFINES_H

enum RIPPLE_TASK_STATE {
	RTS_OPEN,
	RTS_ACCEPTED,
	RTS_STARTED,
	RTS_COMPLETED,
	RTS_CLOSED, //positive confirmation
	RTS_CANCELED
};

enum RIPPLE_LOG_FLAVOR {
	RLF_CREATED,
	RLF_NOTE,
	RLF_FORWARDED,
	RLF_FEEDBACK,
	RLF_DECLINED,
	RLF_ACCEPTED,
	RLF_STARTED,
	RLF_COMPLETED,
	RLF_REOPENED,
	RLF_CLOSED,
	RLF_CANCELED
};
#endif //RIPPLEDEFINES_H
